site_name: WinLocal - dokumentation
repo_url: https://gitlab.lim.bz/dev/wl-dokumentation
site_description: WinLocal documentation
site_author: Olia Kalniei
markdown_extensions:
  - toc:
      permalink: '#'
nav:
  - Introduction: 'index.md'
  - Functionalities:
    - Admin:
      - 'User Accounts': 'admin/user-accounts.md'
      - 'Subscription Plans': 'admin/subscription-plans.md'
      - 'Promo Code Manager': 'admin/promo-code-manager.md'
      - 'Franchise Manager': 'admin/franchise-manager.md'
      - 'Create User': 'admin/create-user.md'
      - 'Export All Contacts': 'admin/export-all-contacts.md'
    - 'Main User Functionalities':
      - 'Dashboard': 'user/dashboard.md'
      - 'Contacts Manager': 'user/contacts-manager.md'
      - 'Winners Manager': 'user/winners-manager.md'
      - 'Staff Members': 'user/staff-members.md'
      - 'My Profile': 'user/my-profile.md'
      - 'Short Links': 'user/short-link.md'
      - 'Notifications': 'user/notifications.md'
    - Onboarding:
      - 'User Info': 'onboarding/user-info.md'
      - 'Payment': 'onboarding/payment.md'
      - 'SMS Campaign': 'onboarding/sms-campaign.md'
    - Campaigns:
      - 'Campaign Manager': 'campaigns/campaign-manager.md'
      - 'Campaign Builder': 'campaigns/campaign-builder.md'
      - 'Push Your Limits': 'campaigns/push-your-limits.md'
      - 'Additional SMS Campaign': 'campaigns/additional-sms-campaign.md'
    - 'Access Actions':
      - 'Login': 'account/login.md'
      - 'Logout': 'account/logout.md'
      - 'Reset password': 'account/reset-password.md'
      - 'Register': 'account/register.md'
      - 'Confirmation Link': 'account/confirmation-link.md'
  - 'Current Franchises':
    - 'Default': 'franchises/default-franchise.md'
    - 'SupportLocal': 'franchises/support-local-franchise.md'

theme:
  name: mkdocs
  nav_style: dark
  navigation_depth: 3
  collapse_navigation: true
  prev_next_buttons_location: none
  sticky_navigation: true
extra_css:
  - css/extra.css